name: flutter_colortrip_app
description: A Flutter app for coloring maps based on photos taken during travels.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12

  # 화면 관련
  google_maps_flutter: ^2.6.0
  provider: ^6.1.2
  flutter_typeahead: ^5.2.0

  # 이미지 처리
  image_picker: ^1.1.2
  palette_generator: ^0.3.3+1
  exif: ^3.3.0

  # 위치, 주소
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  permission_handler: ^11.0.1
  location: ^8.0.0

  # JSON, 기타
  intl: ^0.19.0
  uuid: ^4.4.0
  geojson: ^1.0.0
  share_plus: ^7.2.1
  

  # Firebase (FlutterFire 권장 버전 반영)
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  flutter_exif_rotation: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/geo/HangJeongDong_ver20250401.geojson
    - assets/map_style.json
    - assets/geo/skorea_municipalities_2018_geo.json
    - assets/geo/skorea_provinces_2018_geo.json
    - assets/geo/sejong.geojson