name: flutter_colortrip_app
description: A Flutter app for coloring maps based on photos taken during travels.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  palette_generator: ^0.3.3
  geocoding: ^2.0.5
  geojson: ^1.0.0
  uuid: ^4.3.3
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map_style.json
    - assets/geo/강원도.geojson
    - assets/geo/경기도.geojson
    - assets/geo/경상남도.geojson
    - assets/geo/경상북도.geojson
    - assets/geo/광주광역시.geojson
    - assets/geo/대구광역시.geojson
    - assets/geo/대전광역시.geojson
    - assets/geo/부산광역시.geojson
    - assets/geo/서울특별시.geojson
    - assets/geo/세종특별자치시.geojson
    - assets/geo/울산광역시.geojson
    - assets/geo/인천광역시.geojson
    - assets/geo/전라남도.geojson
    - assets/geo/전라북도.geojson
    - assets/geo/제주특별자치도.geojson
    - assets/geo/충청남도.geojson
    - assets/geo/충청북도.geojson
