// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1CPrR8rqDrji-nSEt1kin5in0lJTU4oc',
    appId: '1:257359194449:android:3a678f19720bced7640b70',
    messagingSenderId: '257359194449',
    projectId: 'flutter-colortrip-36a9a',
    storageBucket: 'flutter-colortrip-36a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6Emuon2zRFJPmz9fjQ8VL26WH-GXfk8',
    appId: '1:257359194449:ios:f2e7582268d0f197640b70',
    messagingSenderId: '257359194449',
    projectId: 'flutter-colortrip-36a9a',
    storageBucket: 'flutter-colortrip-36a9a.firebasestorage.app',
    androidClientId: '257359194449-5mdgh182e2q8d7g5ndn9q2eh64n78kt7.apps.googleusercontent.com',
    iosClientId: '257359194449-taee1dc7m98afbbfr0r10fljupqcg1hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterColortripApp',
  );

}